export const actiontypes = {
  FETCH_DATA_REQUEST: "FETCH_DATA_REQUEST",
  FETCH_DATA_SUCCESS: "FETCH_DATA_SUCCESS",
  FETCH_DATA_FAILURE: "FETCH_DATA_FAILURE",
  // FETCT_DATA_IMAGES : "FETCT_DATA_IMAGES",
  SELECTEDBREED : "SELECTEDBREED",
}